<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net452</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>Netdesk.Agent.VncHelper</AssemblyName>
    <RootNamespace>NetdeskAgent.VncHelper</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Netdesk.Agent.Common\Netdesk.Agent.Common.csproj" />
  </ItemGroup>

</Project>
